title:       Megas的博客
author:      Megas
name:        Liu Yinian
email:       megas.nmsis@hotmail.com
github:      ErythroME
permalink:   /:category/:year/:month/:day/:title
baseurl:     ""
url:         "http://erythrome.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:   megasblog
# duoshuo_shortname:  Megas'-Blog

# Social icons
show_social_icons: true
github_username:   ErythroME
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true

# Resource settings
safe: false
cdn_url: 

exclude: [vendor]
